import { CharacterHeader } from "@/components/character";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Character",
  description: "Generated by create next app",
};

export default function CharacterPage() {
  return (
    <div className="w-full flex justify-center">
      <main className="shadow-lg border-x border-stone-200 min-h-screen flex flex-col gap-8">
        <CharacterHeader className="p-12 pb-6 border-b border-stone-200"/>
      </main>
    </div>
  );
}
