import type { Metadata } from "next";
import { Geist_Mono, Spectral } from "next/font/google";
import "./globals.css";

const spectralSans = Spectral({
  variable: "--font-spectral-sans",
  subsets: ["latin", 'cyrillic'],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spectralSans.variable} ${geistMono.variable} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}
