import type { Metadata } from "next";
import { Geist_Mono, Spectral } from "next/font/google";
import "./globals.css";

const spectralSans = Spectral({
  variable: "--font-spectral-sans",
  subsets: ["latin", 'cyrillic'],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spectralSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <footer className="px-12 flex flex-col items-center gap-2 mt-6 mb-12">
          <span className="block text-sm text-stone-400">
            Destiny Draft · 2026 · Made with &lt;3 by <a className="text-primary-500 underline" href="https://github.com/vistoriel" target="_blank" rel="noopener noreferrer">vistoriel</a>
          </span>
        </footer>
      </body>
    </html>
  );
}
