import { CharacterDetails } from "@/components/character";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Character",
  description: "Generated by create next app",
};

export default function CharacterDetailsPage() {
  return (
    <CharacterDetails className="px-12 pt-6"/>
  );
}
